name: Daily Bing Search Automation

on:
  schedule:
    # Runs daily at 3:30 AM UTC (9:00 AM IST)
    - cron: "30 3 * * *"
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  bing-search-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          # Get the latest ChromeDriver version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1-3)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")

          # Download and install ChromeDriver
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify installation
          chromedriver --version
          google-chrome --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.15.0
          pip install webdriver-manager==4.0.1

      - name: Display environment info
        run: |
          echo "Python version: $(python --version)"
          echo "Pip version: $(pip --version)"
          echo "Chrome version: $(google-chrome --version)"
          echo "ChromeDriver version: $(chromedriver --version)"
          echo "Current time (UTC): $(date -u)"
          echo "Current time (IST): $(TZ='Asia/Kolkata' date)"

      - name: Run Bing search automation
        env:
          OUTLOOK_USERNAME: ${{ secrets.OUTLOOK_USERNAME }}
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
        run: |
          echo "🚀 Starting daily Bing search automation..."
          python bing_search.py

      - name: Upload logs (if needed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: |
            *.log
            screenshots/
          retention-days: 7
