name: Daily Bing Search Automation

on:
  schedule:
    # Runs daily at 3:30 AM UTC (9:00 AM IST)
    - cron: "30 3 * * *"
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  bing-search-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install and setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Verify Chrome and ChromeDriver installation
        run: |
          echo "Chrome version: $(google-chrome --version)"
          echo "ChromeDriver version: $(chromedriver --version)"
          echo "ChromeDriver location: $(which chromedriver)"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.15.0

      - name: Display environment info
        run: |
          echo "Python version: $(python --version)"
          echo "Pip version: $(pip --version)"
          echo "Current time (UTC): $(date -u)"
          echo "Current time (IST): $(TZ='Asia/Kolkata' date)"

      - name: Run Bing search automation
        env:
          OUTLOOK_USERNAME: ${{ secrets.OUTLOOK_USERNAME }}
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
        run: |
          echo "🚀 Starting daily Bing search automation..."
          python bing_search.py

      - name: Upload logs (if needed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: |
            *.log
            screenshots/
          retention-days: 7
